### ISSUE TITLE
Suggestion: Delay before placing blocks

### ISSUE THREAD

**Issue by Alex-Meyer** [crkellen/bands#63]
Currently there is no delay between switching to build mode and being able to place blocks. This allows players to, on reaction to being shot, switch to build mode and instantly place a block as a shield. Hypothetically a very skilled player could abuse this to avoid ever being shot. A delay before being able to place blocks, or making a switch to build mode take a short amount of time would avoid this.

**Comment by crkellen** [comment]
I have two thoughts on this subject:

1. I really enjoy the idea that I can block attacks by placing blocks, but obviously as you pointed out, a skilled player could avoid taking hits.

2. Since I do believe I will be changing the rifle to a hitscan, I think that would clear up some of the issues with this.

In total, I don't think a delay is a bad thing to have, so I will look into adding this.

**Comment by crkellen** [comment]
Added in v0.4.6, cooldown of 1 second after swapping to build mode, cooldown of 1 second after placing a block. Should help prevent block spam/hiding from players
