### ISSUE TITLE
Bullet spawns in wrong place

### ISSUE THREAD

**Issue by cdbone** [crkellen/bands#97]
**Please fill out this Issue template to the best of your ability!**

#### Type of Issue
- [] This Issue is a Bug
- [ ] This Issue is a Feature Request
- [ x] This Issue is a Design Issue/Request

**Hint:** *Design Issues or Requests are changes to existing features, not new ones.*

### Description of the Issue:
Bullet spawns near the left hand on M1 Garand instead of its barrel

### Steps to reproduce the Issue (For Bugs):

- [x] I am using Google Chrome
- [ ] I am using Mozilla Firefox
- [ ] I am using *YOUR_BROWSER*

**Comment by crkellen** [comment]
This is due to two factors:
1. Because bullets are handled on the server, visual updates are milliseconds behind the actual, and therefore can sometime appear to spawn in the incorrect location.
2. The current spawn location of bullets is the 0,0 position of the player, in other words, dead center of the player. For now, the main reason this exists is to prevent missing a player who is on top of you.

I will move it again, as I have in the past, or find a better solution.

**Comment by crkellen** [comment]
After fiddling with values, I believe it's best to just move the gun to the correct position.
Currently the gun is a few pixels off from the center of the player, and shifting the location of the Y of the bullet would cause bullets to be completely shifted from actual aim.

Therefore I am going to close this and start a new issue (#98)
